run:
  timeout: 5m
  tests: true

linters-settings:
  revive:
    severity: error
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - revive      
    - gocritic     
    - gocyclo      
    - bodyclose    
    - gosec        

issues:
  exclude-use-default: false