name: Proto

on:
  pull_request:
    paths:
      - 'api/proto/**'
      - 'buf.yaml'
      - 'buf.gen.yaml'

jobs:
  lint:
    name: Buf lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Buf
        uses: bufbuild/buf-action@v1
        with:
          version: '1.34.0'
          lint: true
          format: true
          breaking: false