name: Proto

on:
  workflow_dispatch: # manual trigger only

jobs:
  lint:
    name: Buf lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v1
        with:
          version: '1.34.0'
          lint: true
          format: true
          breaking: false
